In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("lab04-iteration.ipynb")

In [2]:
# run this cell
import numpy as np

# Lab 04: Loops

Goals of Lab 4:
* Build a mental model for `for` and `while` loops
* Write code with `while`
* Write code with `for`
* Learn more about `np.arange`

**Data 6 note**: Data 6 only uses `for` loops and does not use `while` loops. However, both are commonly used in programming, and understanding `while` will get you more comfortable with `for`.

**Remember**: Run the Otter cell *and* the NumPy cell at the top of this page!


<br/><br/>
<hr style="border: 5px solid #003262;" />
<hr style="border: 1px solid #fdb515;" />

# Part 1, Tutorial: Two Different Types of Loops

From [CS 88 Lab 01](https://cs88-website.github.io/sp22/lab/lab01/).

There are two main types of loops, the while and for loop. They are both used to run a block of code an arbitrary number of times, however, they have different ways of doing it. Take a look at the differences in the table below.

### While Loops

Structure: 
```
<initialization statements>
while <predicate expression>:
    <body statements>
```

Evaluation:
1. Evaluate the `<predicate expression>`. If it's satisfied (the expression evaluates to a True boolean value) go to step 2, otherwise exit loop.
2. Execute the `<body statements>`.
3. Repeat steps 1 and 2 in order until the `<predicate expression>` is *not* satisfied<br/>(i.e., until the `<predicate expression;>` evaluates to a `False` value). | 

Example: 

In [4]:
# just run this cell
i = 0
while i <= 2:
    print(i)
    i = i + 1

0
1
2


In [5]:
i

3

Notes: 
* Normally, the `<predicate expression>` will rely on one or many of the variables defined in the `<initialization statements>`.
* Lastly, the `<body statements>` will have an "update", which will bring make the `<predicate expression>` tend toward a `False` value so there isn't an infinite loop.
* There are some execptions to these previous two rules, but they will rarely be used in this class.

### For Loops

We cover a very specific type of for-loop in this course:

```
<initialization statements>
for <name> in np.arange(n):
    <body statements>
```

1. Let `n` be an integer value. Bind the counter, `<name>`, to 0.
1. If `<name> >= n`, exit the loop.
1. Execute the `<body statements>`.
1. Bind counter `<name>` to `<name> + 1`.
1. Continue steps 2 through 4.

Notes:
* The for-loop effectively repeats the loop body `n` times, where every pass through, the `<name>` binds to the number of times the loop has been executed so far.
* The `<body statements>` doesn't update the `<name>` because step 4 has the update already.
* The function `np.arange()` is from the NumPy package, which we will see more in Data 6. For now, just make sure that you have run the `import numpy as np` line at the top of this program.
* There are other structures to the for loop, which we won't cover in this class.

Example (compare/contrast it to the while loop example!):

In [6]:
for i in np.arange(3):
    print(i)

0
1
2


In [8]:
np.arange(3)

array([0, 1, 2])

**Note**: If you're getting `NameError: name 'np' is not defined`, make sure to import the NumPy `np` module at the top of this page.


<br/><br/>
<hr style="border: 5px solid #003262;" />
<hr style="border: 1px solid #fdb515;" />

# Part 2: What Would Python Do? (WWPD)

From [CS 88 Lab 01](https://cs88-website.github.io/sp22/lab/lab01/).


# Question 1

What would Python do? **Please try doing this by hand before running the cell itself.**

### Question 1a

In [9]:
n = 3
while n >= 0:
    n -= 1
    print(n)

2
1
0
-1


### Question 1b

**Hint for the below cell:** Make sure your while loop conditions eventually evaluate to a false value, or they'll never stop! Pressing the Stop" button at the top of the notebook will stop the Python kernel.

In [10]:
positive = 27
while positive:
    print("positive?")
    positive -= 3

positive?
positive?
positive?
positive?
positive?
positive?
positive?
positive?
positive?


Before proceeding, please comment out the above cell line-by-line, or by selecting all and pressing `Ctrl-/`. If you don't, then restarting kernel + running all cells will produce an infinite loop.

### Question 1c

In [1]:
positive = -9
negative = -12
while negative:
    if positive:
         print(negative)
    else:
        print(positive)
    positive += 3
    negative += 3

-12
-9
-6
0


<br/><br/>

---

# Question 2

Adapted from Stanford's [CS 106A Assignment 2](https://web.stanford.edu/class/archive/cs/cs106a/cs106a.1226/handouts/07-assignment2.html).

In this question, you will trace code and compare `while` with `for` loops. In both parts, try writing down what the Python cell will print **by hand** before running the code.

## Question 2a

What will the following code print?

In [11]:
def mystery():
    x = 3
    x = 5 - x / 2
    print(x)

x = 1
while x < 20:
    print("x = " + str(x))
    mystery()
    x *= 2
print("x = " + str(x))

x = 1
3.5
x = 2
3.5
x = 4
3.5
x = 8
3.5
x = 16
3.5
x = 32


## Question 2b

`for` loop. Note that the `mystery()` function was defined when you ran the previous cell.

What will the following code print? How is it different from the previous part?

In [12]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
x = 1
for i in np.arange(20):
    print("x = " + str(x))
    mystery()
    #x = x * 2
    x *= 2
print("x = " + str(x))

x = 1
3.5
x = 2
3.5
x = 4
3.5
x = 8
3.5
x = 16
3.5
x = 32
3.5
x = 64
3.5
x = 128
3.5
x = 256
3.5
x = 512
3.5
x = 1024
3.5
x = 2048
3.5
x = 4096
3.5
x = 8192
3.5
x = 16384
3.5
x = 32768
3.5
x = 65536
3.5
x = 131072
3.5
x = 262144
3.5
x = 524288
3.5
x = 1048576


<br/><br/>

---

# Question 3: Square So Slow...

From [CS 61A Discussion 01](https://cs61a.org/disc/disc01/).

What is the result of evaluating the following code? Make sure to uncomment the line `square(so_slow(5))`.

**Hint**: What happens to `x` over time?

**Debug note**: To stop running a cell, hit the 'Stop' button (Square icon) above.

In [15]:
def square(x):
    print("here!")
    return x * x

def so_slow(num = 5):
    x = num
    #x = 5
    while x < 10:
        # x = 10
        x = x + 1
    return x / 1

# uncomment this line 
square(so_slow(5))

here!


100.0

Before proceeding, please comment out the `square(so_slow(5))` line. If you don't, then restarting kernel + running all cells will produce an infinite loop.


<br/><br/>
<hr style="border: 5px solid #003262;" />
<hr style="border: 1px solid #fdb515;" />


# Part 3: Programming Exercises


From [CS 88 Discussion 01](https://cs88-website.github.io/sp22/disc/disc01.pdf) and [CS61A Lab 01](https://cs61a.org/lab/lab01/#error-messages), as well as Stanford's [CS 106A Assignment 2](https://web.stanford.edu/class/archive/cs/cs106a/cs106a.1226/handouts/07-assignment2.html).

<br/><br/>

---

# Question 4: Liftoff!

Implement the below "liftoff" functions that print out the calls for a spaceship that is about to launch. Countdown the numbers from 10 to 1 and then write "Liftoff!"

**Note 1**: Note the blank line between each printed number! You can achieve this with a call to `print()` with no arguments.

**Note 2**  there is no autograder for this function! When running the cell below, a correct implementation will output nothing and print the following:


```
10

9

8

7

6

5

4

3

2

1

Liftoff!
```

## Question 4a

First, try implementing the `liftoff_while` function with a `while` loop.

**Debugging note**: If your code gets stuck, stop the cell with the "Stop" (Square) button above.

In [16]:
def liftoff_while():
    i = 10
    
    while i >=1:
        print(i)
        print()
        i -= 1
        
    print("Liftoff!")

liftoff_while()

10

9

8

7

6

5

4

3

2

1

Liftoff!


## Question 4b

Next, try implementing the `liftoff_for` function with a `for` loop.

In [ ]:
def liftoff_for():
    ...

liftoff_for()

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/popularity_contest/reporter.py", line 105, in report_popularity
    libraries = get_used_libraries(initial_modules, current_modules)
  File "/opt/conda/lib/python3.9/site-packages/popularity_contest/reporter.py", line 74, in get_used_libraries
    all_packages = get_all_packages()
  File "/opt/conda/lib/python3.9/site-packages/popularity_contest/reporter.py", line 51, in get_all_packages
    for f in dist.files:
TypeError: 'NoneType' object is not iterable


In [20]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Question 4c

Which loop worked better for implementing liftoff, `for` or `while`? What do you think were the tradeoffs?

_Write your answer, replacing this line._

<br/><br/>

---

# Question 5: Add in Range

Complete `add_in_range`, which returns the sum of all integers between `start` and `stop` (inclusive).

Your function should correctly evaluate the following:

``` 
add_in_range(3, 5)  # 12
add_in_range(1, 10)  # 55
```

**Note**: Would you use a `for` loop or a `while` loop for this function? Why? (There is no right answer--it is up to you! Try implementing both ways if you have time.)

**Note 2**: Make sure that you are using `return` rather than `print`.

In [ ]:
def add_in_range(start, stop):
    ...

# edit the below line as needed for testing
add_in_range(3, 5)

In [ ]:
grader.check("q5")

<br/><br/>

---

# Question 6: Falling Factorial
Let's write a function `falling()`, which is a "falling" factorial that takes two arguments, `n` and `k`, and returns the product of `k` consecutive numbers, starting from `n` and working downwards. When `k` is `0`, the function should return `1`.


Your function should correctly evaluate the following:

``` 
falling(6, 3)  # return 120, which is 6 * 5 * 4
falling(4, 3)  # return 24, which is 4 * 3 * 2
falling(4, 1)  # 4
falling(4, 0)  # 1
```

**Note**: Make sure that you are using `return` rather than `print`.

In [4]:
def falling(n, k):
    """Compute the falling factorial of n to depth k."""
    total = 1
    for i in np.arange(k):
        total*=n
        n-=1
    return total
    
# edit the below line as needed for testing
falling(6, 3)

120

In [5]:
grader.check("q6")

q6 results: All test cases passed!

<br/><br/>

---

# Question 7: Sum Digits

From [CS 88 Lab 01](https://cs88-website.github.io/sp22/lab/lab01/).

Write a function that takes in a nonnegative integer and sums its digits. (Using integer division `//` and modulo `%` might be helpful here!)

Your implementation should correctly evaluate the following:
```
sum_digits(10)         # returns 1, because 1 + 0 = 1
sum_digits(4224)       # returns 12, because 4 + 2 + 2 + 4 = 12
sum_digits(1234567890) # 45
```

In [32]:
def sum_digits(n):
    total = 0
    while n > 0:
        last_dig = n % 10
        total = total + last_dig
        n = n // 10
    return total

# edit the below line as needed for testing
sum_digits(1234567890)

45

In [30]:
grader.check("q7")

q7 results: All test cases passed!

<br/><br/>

---

# Question 8: Fizzbuzz

From [CS 61A Discussion 01](https://cs61a.org/disc/disc01/).

Implement the fizzbuzz sequence, which prints out a single statement for each number from `1` to `n`. For a number `i`,

* If `i` is divisible by 3 only, then we print "fizz".
* If `i` is divisible by 5 only, then we print "buzz".
* If `i` is divisible by both 3 and 5, then we print "fizzbuzz".
* Otherwise, we print the number `i` by itself.

Implement `fizzbuzz(n)` below.

**Note**  there is no autograder for this function! When running the cell below, a correct implementation will call `fizzbuzz(16)`, output nothing, and print the following:

```
1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz
16
```

In [ ]:
def fizzbuzz(n):
    """
    This function should only print values. It should not return anything.
    """
    ...


# edit the below line as needed for testing
fizzbuzz(16)

<br/><br/>

---

# Question 9: Prime Numbers

Write a function that returns `True` if a positive integer `n` is a prime number and `False` otherwise.

A prime number $n$ is a number that is not divisible by any numbers other than 1 and $n$ itself. For example, 13 is prime, since it is only divisible by 1 and 13, but 14 is not,
since it is divisible by 1, 2, 7, and 14.

**Hint**: use the `%` operator: `x % y` returns the remainder of `x` when divided by `y`.

Your implementation should correctly evaluate the following:
```
is_prime(10)   # False
is_prime(7)    # True
```

In [ ]:
def is_prime(n):
    ...

# edit the below line as needed for testing
is_prime(10)

In [ ]:
grader.check("q9")

<br/><br/>
<hr style="border: 5px solid #003262;" />
<hr style="border: 1px solid #fdb515;" />

# Part 4: Advanced `np.arange`  for Data 6

Last part of this lab! (Part 5 is bonus)

### Tutorial 

You will see a more involved version of the `for` loop in Data 6:

```
for <name> in np.arange(start, stop, step):
    <body statements>
```

The counter `<name>` binds to the value `start`, then `start + step`, then `start + 2*step`, and so on until `<name> >= stop`.

Here's an example:

In [38]:
for i in np.arange(13, 10, -1):
    print(i)

13
12
11


Above, note that the last value of `i` to be printed is `9`, because the next value `12` is greater than the stop value of `10`.

Here's another example, showing that steps can be taken "backwards":

In [39]:
for x in np.arange(20, 15, -1):
    print(x)

20
19
18
17
16


Finally, note that unlike `while` loops, invalid "ranges" will simply lead to no loop iterations. The following code will not print anything:

In [41]:
# no numbers starting from 10 and *increasing* to 5
for counter in np.arange(10, 5, -1):
    print(counter)

10
9
8
7
6


<br/><br/>

---

# Question: More Liftoff

Implement the liftoff function below, but now with a `for` loop that uses a customized `np.arange(start, stop, step)` structured `for` loop.

A correct implementation will output nothing and print the following:


```
10

9

8

7

6

5

4

3

2

1

Liftoff!
```

In [43]:
def liftoff_arange():
    for i in np.arange(10,0,-1):
        print(i)
        print()
    print("Liftoff!")

liftoff_arange()

10

9

8

7

6

5

4

3

2

1

Liftoff!


In [44]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

<br/><br/>

---

# Question: More Add in Range

Implement the function below, which returns the sum of all integers between `start` and `stop` (inclusive) but uses a customized `np.arange(start, stop, step)` structured `for` loop.

Your function should correctly evaluate the following:

``` 
    add_in_range(3, 5)  # 12
    add_in_range(1, 10)  # 55
```

In [47]:
def add_in_range_arange(start, stop):
    total =0
    for num in np.arange(start,stop+1):
        total+= num
    return total

# edit the below line as needed for testing
add_in_range_arange(3, 5)

12

In [48]:
grader.check("q5b")

q5b results: All test cases passed!


<br/><br/>
<hr style="border: 5px solid #003262;" />
<hr style="border: 1px solid #fdb515;" />

# Part 5, Bonus: More Practice

From [CS 88 Lab 01](https://cs88-website.github.io/sp22/lab/lab01/) and [CS61A Lab 01](https://cs61a.org/lab/lab01/#error-messages).

There are 6 bonus questions. Feel free to complete any, all, or none of them.

# Question 2 (continued): More WWPD

This code tracing question is a continuation of Question 2's WWPD from earlier in this lab. We've included the previous parts of the question below for your convenience.

In [ ]:
# question 2a, repasted for your convenience.
# just run this cell

def mystery():
    x = 3
    x = 5 - x / 2
    print(x)

x = 1
while x < 20:
    print("x = " + str(x))
    mystery()
    x *= 2
print("x = " + str(x))

In [ ]:
# question 2b, repasted for your convenience.
# just run this cell

x = 1
for i in np.arange(20):
    print("x = " + str(x))
    mystery()
    x *= 2
print("x = " + str(x))

In this case, we will still work with a `for` loop, but now notice that the loop counter variable has changed to `x` (instead of `i`). How does this change what is printed from the below cell?

In [ ]:
# question 2c: WWPD?
x = 1
for x in np.arange(20):
    print("x = " + str(x))
    mystery()
    x *= 2
print("x = " + str(x))

<br/><br/>

---

# Question 10: Digit Position Match

A number has a digit-position match if the `i`th-to-last digit is `i`. For example, `980` has the `0`th-to-last digit as `0`. Or `98276` has the `2`nd-to-last digit as a `2`.


Write a function that determines if a number `n` has a digit-position match at a `k`th-to-last digit `k`.

A correct implementation will return the following:
```
digit_pos_match(980, 0)      # True
digit_pos_match(980, 2)      # False
digit_pos_match(98276, 2)    # True
digit_pos_match(98276, 3)    # False
```

In [ ]:
def digit_pos_match(n, k):
    ...
    
digit_pos_match(980, 0)

<br/><br/>

---

# Question 11: Triangular numbers

The $n$th triangular number is defined as the sum of all integers from 1 to $n$, i.e.

```
1 + 2 + ... + n
```

The closed-form formula for the $n$th triangular number is

```
(n + 1) * n / 2
```

Define the function `triangular_sum`, which takes an integer `n` and returns the sum of the first `n` triangular numbers, while printing each of the triangular numbers between `1` and the `n`th triangular number.

A correct implementation will do the following: When the below code is run,
```
t_sum = triangular_sum(5)
t_sum
```

Python will print:
```
1
3
6
10
15
```

and output `35`.

In [ ]:
def triangular_sum(n):
    ...

# edit the below line as needed for testing
t_sum = triangular_sum(5)
t_sum

<br/><br/>

---

# Question 12: K-Occurrence

Complete `k_occurrence`, a function which returns the number of times the digit `k` appears in `num`. `0` is considered to have no digits.

A correct implementation will return the following: 
```
k_occurrence(5, 10)    # 0
k_occurrence(5, 5115)  # 2
k_occurrence(0, 100)   # 2
k_occurrence(0, 0)     # 0
```

In [ ]:
def k_occurrence(k, num):
    ...

# edit the below line as needed for testing   
k_occurrence(5, 10)

<br/><br/>

---

# Question 13: Double Eights
Write a function that takes in a number and determines if the digits contain two adjacent 8s (i.e., two eights in a row).

A correct implementation will return the following: 

```
double_eights(8)         # False
double_eights(88)        # True
double_eights(2882)      # True
double_eights(880088)    # True
double_eights(12345)     # False
double_eights(80808080)  # False
```

In [ ]:
def double_eights(n):
    ...

# edit the below line as needed for testing   
double_eights(8)

<br/><br/>

---

# (Challenge) Question 14: Right Triangle
Write a function that takes in 3 sides `a`, `b`, and `c` and checks to see if they can be possible lengths of the sides of a right triangle. Recall Pythagorean's Theorem:

```
x^2 + y^2 = z^2 # where z is the hypotenuse
```

**Hint**: Find the smallest and largest side first.

A correct implementation will return the following:
```
right_triangle(1, 1, 1)   # False
right_triangle(5, 3, 4)   # True
right_triangle(8, 10, 6)  # True
```

In [ ]:
def right_triangle(a, b, c):
    ...

# edit the below line as needed for testing   
right_triangle(1, 1, 1)

### 

# Done!

That's it! There's nowhere for you to submit this, as labs are not assignments. However, please ask any questions you have with this notebook in lab or on Slack.

**Note**: If you are having trouble running the "check all" grader cell, make sure you comment out the code for Questions 1b and Question 3! They produce **infinite loops** if left in.

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. The cell below will generate a zip file for you to submit. **Please save before exporting!**

In [ ]:
# Save your notebook first, then run this cell to export your submission.
grader.export(pdf=False, run_tests=True)